#!/usr/bin/zsh

source /home/lambda/.config/zsh/zsh_variables

#* output coloring variables
normal=$( tput sgr 0 );
red=$( tput setaf 1 );
green=$( tput setaf 2 );
yellow=$( tput setaf 3 );
blue=$( tput setaf 4 );
magenta=$( tput setaf 5 );
cyan=$( tput setaf 6 );
white=$( tput setaf 7 );

# utilitiy for only echoing to output when not in quiet mode
out_echo() {
	[[ $quietFlag == "true" ]] || echo $@
}

if [[ ${UID} != 0 ]]; then
    echo "${red}$( basename $0 )${normal}: This script must be run as root or with sudo permissions. Please run using sudo."
    exit 1
fi

# # Check for flags
quietFlag="false"
verboseFlag="false"
while getopts ":qv" flag; do
	case ${flag} in
		q)
			quietFlag="true"
			;;
		v)
			verboseFlag="true"
			;;
		\?)
			echo -e "${red}$( basename $0 )${reset}: The option -${OPTARG} is invalid." >&2
			exit 404
			;;
	esac
done

[[ $quietFlag == "true" ]] && notify-send "Actualizando paquetes" "Ejecutando el script de system-update..."

# # Log usage
echo "$( date +'%F %T' ) $( basename $0 )" >> $LOGS/general.log 

echo "#? ========= $( date +'%F %T' ) =========" >> $LOGS/system-update.log

echo "#* --------- Updating database ---------" >> $LOGS/system-update.log
out_echo "${cyan}$( basename $0 )${normal}: Updating apt database...${normal}"

{ apt-get update 2>&1; } >> $LOGS/system-update.log

if [[ $pipestatus == "0" ]]; then
    out_echo "${green}$( basename $0 )${normal}: Database updated${normal}"
else
    out_echo "${red}$( basename $0 )${normal}: Error updating database!${normal}"
    exit 2
fi

if [[ $verboseFlag == "true" && $quietFlag != "true" ]]; then
    echo "${blue}$( basename $0 )${normal}: Packages to be updated:"
    apt list --upgradable
fi

echo "#* --------- Upgrading packages ---------" >> $LOGS/system-update.log
out_echo "${cyan}$( basename $0 )${normal}: Upgrading apt packages...${normal}"

{ apt-get dist-upgrade -y 2>&1; } >> $LOGS/system-update.log

if [[ $pipestatus == "0" ]]; then
    out_echo "${green}$( basename $0 )${normal}: Packages installed correctly${normal}"
	[[ $quietFlag == "true" ]] && notify-send "¡Mejora completa!" "Paquetes actualizados correctamente"
else
    out_echo "${red}$( basename $0 )${normal}: Error upgrading packages!${normal}"
	[[ $quietFlag == "true" ]] && notify-send "¡Error mejorando!" "Los paquetes no fueron actualizados" --urgency="critical"
    exit 3
fi
